graphhopper:
  datareader.file: ""
  graph.location: graph-cache

  profiles:
    - name: foot
      custom_model_files: [foot.json]

  profiles_ch: []
  profiles_lm: []

  graph.encoded_values: foot_access, foot_priority, foot_average_speed, foot_road_access, hike_rating, mtb_rating, country, road_class

  prepare.min_network_size: 2
  prepare.subnetworks.threads: 1
  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.non_ch.max_waypoint_distance: 1000000
  import.osm.ignored_highways: motorway,trunk
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0

logging:
  appenders:
    - type: console
